### ISSUE TITLE
Github account required

### ISSUE THREAD

**Issue by mguida22** [HackCU/HackCU2016#53]
Hey! Some of my friends are interested in coming but have never programmed before and do not have github accounts. I was going to help them get setup with everything they need during the hackathon including github accounts.

Is it possible to make this not required? I think if it's not required it'll make it less intimidating to people who have never programmed and/or never heard of github.

**Comment by jessiemblack** [comment]
Hey! Sorry about that! It shouldn't be a required field for them to apply now.

**Comment by mguida22** [comment]
Thanks :satisfied:
